# Generated by Django 5.2.17 on 2026-09-01 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oposiciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='slug')),
                ('body', models.TextField(blank=True, verbose_name='texto (markdown)')),
                ('body_html', models.TextField(blank=True, editable=False, verbose_name='texto renderizado')),
                ('draft_title', models.CharField(blank=True, max_length=300, verbose_name='título del borrador')),
                ('draft_body', models.TextField(blank=True, verbose_name='texto del borrador (markdown)')),
                ('draft_saved_at', models.DateTimeField(blank=True, null=True, verbose_name='último autoguardado')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='estado')),
                ('moderation_status', models.CharField(choices=[('approved', 'Aprobado'), ('flagged', 'Señalado'), ('taken_down', 'Retirado')], default='approved', max_length=10, verbose_name='estado de moderación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('oposiciones', models.ManyToManyField(blank=True, related_name='posts', to='oposiciones.oposicion', verbose_name='oposiciones')),
            ],
            options={
                'verbose_name': 'apunte',
                'verbose_name_plural': 'apuntes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'moderation_status'], name='post_status_idx')],
            },
        ),
    ]
