# Generated by Django 5.2.17 on 2026-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'Aceptado'), ('rejected', 'Rechazado')], max_length=10, verbose_name='decisión')),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, verbose_name='hash de user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'evento de consentimiento',
                'verbose_name_plural': 'eventos de consentimiento',
            },
        ),
    ]
