# Generated by Django 5.2.17 on 2026-08-31 12:44

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # pg_trgm (GIN trigram index on nombre) is created by core.0001.
        ('core', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('ambito', models.CharField(choices=[('estado', 'Estatal'), ('autonomica', 'Autonómica'), ('local', 'Local')], max_length=20, verbose_name='ámbito')),
                ('comunidad', models.CharField(blank=True, choices=[('andalucia', 'Andalucía'), ('aragon', 'Aragón'), ('asturias', 'Principado de Asturias'), ('baleares', 'Illes Balears'), ('canarias', 'Canarias'), ('cantabria', 'Cantabria'), ('castilla-la-mancha', 'Castilla-La Mancha'), ('castilla-y-leon', 'Castilla y León'), ('cataluna', 'Cataluña'), ('ceuta', 'Ceuta'), ('comunidad-valenciana', 'Comunitat Valenciana'), ('extremadura', 'Extremadura'), ('galicia', 'Galicia'), ('la-rioja', 'La Rioja'), ('madrid', 'Comunidad de Madrid'), ('melilla', 'Melilla'), ('murcia', 'Región de Murcia'), ('navarra', 'Comunidad Foral de Navarra'), ('pais-vasco', 'País Vasco')], help_text='Solo para oposiciones autonómicas o locales.', max_length=30, verbose_name='comunidad autónoma')),
                ('cuerpo', models.CharField(blank=True, max_length=200, verbose_name='cuerpo')),
                ('escala', models.CharField(blank=True, max_length=200, verbose_name='escala')),
                ('grupo', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('C1', 'C1'), ('C2', 'C2'), ('E', 'E (agrupaciones profesionales)')], max_length=2, verbose_name='grupo')),
                ('titulacion_requerida', models.CharField(blank=True, max_length=300, verbose_name='titulación requerida')),
                ('sistema_selectivo', models.CharField(choices=[('oposicion', 'Oposición'), ('concurso-oposicion', 'Concurso-oposición'), ('concurso', 'Concurso')], default='oposicion', max_length=20, verbose_name='sistema selectivo')),
                ('organismo_convocante', models.CharField(blank=True, max_length=300, verbose_name='organismo convocante')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacada en portada')),
                ('homepage_order', models.IntegerField(default=0, verbose_name='orden en portada')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'oposición',
                'verbose_name_plural': 'oposiciones',
                'ordering': ['homepage_order', 'nombre'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['nombre'], name='oposicion_nombre_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('referencia_boe', models.CharField(blank=True, max_length=100, verbose_name='referencia BOE')),
                ('url_boe', models.URLField(blank=True, verbose_name='URL del BOE')),
                ('plazas', models.PositiveIntegerField(blank=True, null=True, verbose_name='plazas')),
                ('plazas_libre', models.PositiveIntegerField(blank=True, null=True, verbose_name='plazas turno libre')),
                ('plazas_discapacidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='plazas reserva discapacidad')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('fecha_limite_solicitud', models.DateField(blank=True, null=True, verbose_name='fecha límite de solicitud')),
                ('estado', models.CharField(choices=[('anunciada', 'Anunciada'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta')], default='anunciada', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('oposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='oposiciones.oposicion', verbose_name='oposición')),
            ],
            options={
                'verbose_name': 'convocatoria',
                'verbose_name_plural': 'convocatorias',
                'ordering': ['-anio', '-fecha_publicacion'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'slug'), name='convocatoria_anio_slug')],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='número')),
                ('titulo', models.CharField(max_length=500, verbose_name='título')),
                ('bloque', models.CharField(blank=True, max_length=200, verbose_name='bloque')),
                ('oposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='oposiciones.oposicion', verbose_name='oposición')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ['oposicion', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('oposicion', 'numero'), name='tema_unico_numero')],
            },
        ),
    ]
