# Generated by Django 5.2.17 on 2026-08-31 12:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # The es_unaccent search configuration and pg_trgm extension used by
        # search_vector and the trigram index are created by core.0001.
        ('core', '0001_extensions'),
        ('oposiciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('source_type', models.CharField(choices=[('official', 'Oficial (BOE, ministerio)'), ('editorial', 'Editorial (elaborado por la redacción)'), ('user', 'Aportado por un usuario')], default='editorial', max_length=10, verbose_name='origen')),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('registered', 'Solo usuarios registrados'), ('private', 'Privado')], default='public', max_length=10, verbose_name='visibilidad')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('flagged', 'Señalado'), ('taken_down', 'Retirado')], default='pending', max_length=10, verbose_name='estado de moderación')),
                ('storage_key', models.CharField(blank=True, max_length=300, verbose_name='clave de almacenamiento')),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA-256')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='tipo MIME')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='tamaño en bytes')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de páginas')),
                ('extracted_text', models.TextField(blank=True, verbose_name='texto extraído')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('ocr_queued', 'En cola de OCR'), ('done', 'Completada'), ('failed', 'Fallida'), ('skipped', 'Omitida')], default='pending', max_length=12, verbose_name='estado de extracción')),
                ('license', models.CharField(choices=[('own_work', 'Obra propia del autor'), ('official_public', 'Documento oficial de libre reutilización'), ('permission_granted', 'Con permiso del titular de los derechos')], max_length=20, verbose_name='licencia')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='descargas')),
                ('tags_text', models.TextField(blank=True, editable=False, verbose_name='etiquetas (denormalizado)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='es_unaccent', weight='A'), '||', django.contrib.postgres.search.SearchVector('tags_text', config='es_unaccent', weight='B'), django.contrib.postgres.search.SearchConfig('es_unaccent')), '||', django.contrib.postgres.search.SearchVector('description', config='es_unaccent', weight='C'), django.contrib.postgres.search.SearchConfig('es_unaccent')), '||', django.contrib.postgres.search.SearchVector(django.db.models.functions.text.Left('extracted_text', 150000), config='es_unaccent', weight='D'), django.contrib.postgres.search.SearchConfig('es_unaccent')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('canonical_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='documents.document', verbose_name='documento canónico')),
                ('convocatoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='oposiciones.convocatoria', verbose_name='convocatoria')),
                ('oposiciones', models.ManyToManyField(blank=True, related_name='documents', to='oposiciones.oposicion', verbose_name='oposiciones')),
                ('temas', models.ManyToManyField(blank=True, related_name='documents', to='oposiciones.tema', verbose_name='temas')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='autor de la subida')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=10, verbose_name='estado anterior')),
                ('to_status', models.CharField(max_length=10, verbose_name='estado nuevo')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor del cambio')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_log', to='documents.document', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'registro de moderación',
                'verbose_name_plural': 'registros de moderación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('reason', models.CharField(choices=[('copyright', 'Infracción de derechos de autor'), ('incorrect', 'Contenido incorrecto'), ('inappropriate', 'Contenido inapropiado'), ('duplicate', 'Duplicado')], max_length=15, verbose_name='motivo')),
                ('detail', models.TextField(verbose_name='detalle')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('reviewing', 'En revisión'), ('resolved', 'Resuelta'), ('dismissed', 'Desestimada')], default='open', max_length=10, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='documents.document', verbose_name='documento')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='denunciante')),
            ],
            options={
                'verbose_name': 'denuncia',
                'verbose_name_plural': 'denuncias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='document_search_gin'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='document_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
