# Generated by Django 5.2.17 on 2026-09-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('oposiciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminos', models.TextField(help_text='Un término por línea. El item coincide si su título contiene alguno de ellos (sin distinguir mayúsculas ni acentos).', verbose_name='términos')),
                ('departamento_contiene', models.CharField(blank=True, help_text='Opcional. Restringe la regla a un organismo convocante.', max_length=200, verbose_name='el departamento contiene')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('oposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_rules', to='oposiciones.oposicion', verbose_name='oposición')),
            ],
            options={
                'verbose_name': 'regla de captura',
                'verbose_name_plural': 'reglas de captura',
                'ordering': ['oposicion__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boletin', models.CharField(choices=[('boe', 'BOE (Boletín Oficial del Estado)')], default='boe', max_length=10, verbose_name='boletín')),
                ('fecha', models.DateField(verbose_name='fecha del boletín')),
                ('status', models.CharField(choices=[('running', 'En curso'), ('ok', 'Completada'), ('no_edition', 'Sin edición'), ('failed', 'Fallida')], default='running', max_length=12, verbose_name='estado')),
                ('items_seen', models.PositiveIntegerField(default=0, verbose_name='items encontrados')),
                ('items_imported', models.PositiveIntegerField(default=0, verbose_name='documentos importados')),
                ('items_duplicate', models.PositiveIntegerField(default=0, verbose_name='duplicados')),
                ('items_failed', models.PositiveIntegerField(default=0, verbose_name='fallidos')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
            ],
            options={
                'verbose_name': 'ejecución de captura',
                'verbose_name_plural': 'ejecuciones de captura',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('boletin', 'fecha'), name='one_run_per_bulletin_day')],
            },
        ),
        migrations.CreateModel(
            name='HarvestedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boletin', models.CharField(choices=[('boe', 'BOE (Boletín Oficial del Estado)')], default='boe', max_length=10, verbose_name='boletín')),
                ('identificador', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='identificador')),
                ('fecha_publicacion', models.DateField(verbose_name='fecha de publicación')),
                ('seccion', models.CharField(blank=True, max_length=200, verbose_name='sección')),
                ('departamento', models.CharField(blank=True, max_length=300, verbose_name='departamento')),
                ('epigrafe', models.CharField(blank=True, max_length=300, verbose_name='epígrafe')),
                ('titulo', models.TextField(verbose_name='título')),
                ('url_pdf', models.URLField(blank=True, max_length=500, verbose_name='URL del PDF')),
                ('url_html', models.URLField(blank=True, max_length=500, verbose_name='URL HTML')),
                ('url_xml', models.URLField(blank=True, max_length=500, verbose_name='URL XML')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='tamaño anunciado')),
                ('status', models.CharField(choices=[('new', 'Pendiente de descarga'), ('imported', 'Importado'), ('duplicate', 'Duplicado (ya existía)'), ('ignored', 'Ignorado'), ('failed', 'Fallido')], default='new', max_length=10, verbose_name='estado')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_items', to='documents.document', verbose_name='documento')),
                ('matched_oposiciones', models.ManyToManyField(blank=True, related_name='harvested_items', to='oposiciones.oposicion', verbose_name='oposiciones detectadas')),
            ],
            options={
                'verbose_name': 'item capturado',
                'verbose_name_plural': 'items capturados',
                'ordering': ['-fecha_publicacion', 'identificador'],
                'indexes': [models.Index(fields=['status', 'fecha_publicacion'], name='item_status_fecha_idx')],
            },
        ),
    ]
